title: 日本語ドキュメント
description: > 
  各種日本語ドキュメントを日本語に翻訳したものたち
baseurl: "/"
url: "https://docs-ja.utakata.work"
twitter_username: yoshiki_utakata 
github_username:  yoshikyoto

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
